version: '3'
services:
    client:
        image: 'unsivilaudio/multi-client-04-29'
        mem_limit: 128m
        hostname: client
    server:
        image: 'unsivilaudio/multi-server-04-29'
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: 'unsivilaudio/multi-worker-04-29'
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    nginx:
        image: 'unsivilaudio/multi-nginx-04-29'
        mem_limit: 128m
        hostname: nginx
        ports:
            - '80:80'
