apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: unsivilaudio/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-srv
            - name: REDIS_PORT
              value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: worker-srv
spec:
  selector:
    component: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
